### ISSUE TITLE
QSG

### ISSUE THREAD

**Issue by Lain-tf** [Lain-tf/copper#6]
- change in-game name to "Rotary Shotgun"
- 20fps animation needs to be synced to attacking
- 1s downtime after firing > .8 seconds
- fix weapon switch being locked / not queued for entire duration
- tie new models and sounds to the weapon (attached)
- reduce / fix aimkick (currently only the first shot fires at the crosshair, and the rest fire below it)
- increase damage (needs to be enough to kill a Hell Knight in a 1 rocket + 1 QSG blast combo)

[qsg_files.zip](https://github.com/khreathor/copper/files/6162592/qsg_files.zip)

**Comment by Juzley** [comment]
Think these should all be sorted now, closing this.
